services:
  - type: web
    name: psb-banking-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: 106472ec4a66767a6690423351bcc087c944a671828caa3b4ee27a6bbf9ac10c5d55342122349c674411951a3879f2ba
      - key: ADMIN_ID
        value: TEAM EXCELLENT MINDS
      - key: ADMIN_PASSWORD
        value: Kcwkl6OQT57VweVSeSjgA7W4
      - key: ENCRYPTION_KEY
        value: cd48f7cf9b62f765a187def78daac0b4695aec55c896069efd92c3daa9a257d0
      - key: GEMINI_API_KEY
        value: 
      - key: DATABASE_PATH
        value: /data/ds_financial.db
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
